spring:
  application:
    name: clima-api

  datasource:
    url: jdbc:mysql://localhost:3307/clima_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: parde4

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true

openweathermap:
  api-url: https://api.openweathermap.org/data/2.5
  api-key: ${WEATHER_API_KEY}